FROM python:3.11-slim

# Sistema
RUN apt-get update && \
    apt-get install -y tesseract-ocr tesseract-ocr-ita && \
    rm -rf /var/lib/apt/lists/*

# App
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Render usa $PORT
CMD gunicorn app:app --bind 0.0.0.0:$PORT
